name: first-exercise-workflow
on: [push, pull_request]

jobs:
  check-python:
    runs-on: ubuntu-latest
    steps:
      - name: check python version
        run: python --version
      - name: check pip version
        run: pip --version
          